# Generated by Django 3.1.3 on 2021-02-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20210221_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='updated_at',
        ),
    ]
