# Generated by Django 3.1.3 on 2021-02-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20210222_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subarticle',
            name='reference_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
