# Generated by Django 3.1.3 on 2021-02-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_mainarticle_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subarticle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='SubArticle/'),
        ),
    ]
