# Generated by Django 3.1.3 on 2021-02-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20210222_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainarticle',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
