# Generated by Django 3.1.3 on 2021-02-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20210223_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainarticle',
            name='short_description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
