# Generated by Django 3.1.3 on 2021-02-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_auto_20210224_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subarticle',
            name='reference_link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
