# Generated by Django 3.1.3 on 2021-02-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_auto_20210224_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainarticle',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
