# Generated by Django 3.1.3 on 2021-02-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_auto_20210224_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subarticle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/SubArticle/'),
        ),
    ]
