# Generated by Django 3.1.3 on 2021-02-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0023_auto_20210224_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='subarticle',
            name='image_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
