# Generated by Django 3.1.3 on 2021-03-01 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0024_subarticle_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubArticleRollBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='SubArticle/')),
                ('image_description', models.CharField(blank=True, max_length=100, null=True)),
                ('title_to_external_link', models.CharField(blank=True, max_length=200, null=True)),
                ('external_link', models.URLField(blank=True, max_length=300, null=True)),
                ('other_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.mainarticle')),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
