# Generated by Django 3.1.3 on 2021-03-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0025_subarticlerollback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subarticlerollback',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='SubArticleRollBack/'),
        ),
    ]
