# Generated by Django 3.1.3 on 2021-03-01 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0026_auto_20210301_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='subarticlerollback',
            name='history_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.subarticle'),
        ),
    ]
